# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XmpefFaGzTvl_JhL-IlzOLUR60x-mMmj
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import pandas as pd
# import shap
# import matplotlib.pyplot as plt
# from sklearn.datasets import load_breast_cancer
# from sklearn.model_selection import train_test_split
# from sklearn.tree import DecisionTreeClassifier
# 
# def main():
#     print("🚀 Explainable Credit Scorecard Prototype")
# 
#     data = load_breast_cancer(as_frame=True)
#     X, y = data.data, data.target
#     print("Dataset Shape:", X.shape)
#     print("Features:", list(X.columns)[:10], "...")
# 
#     X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# 
#     model = DecisionTreeClassifier(max_depth=3, random_state=42)
#     model.fit(X_train, y_train)
# 
#     sample = X_test.iloc[[0]]
#     proba = model.predict_proba(sample)[0][1]
#     credit_score = round(proba * 100, 2)
#     print(f"Predicted Credit Score: {credit_score}/100")
# 
#     explainer = shap.Explainer(model, X_train)
#     shap_values = explainer(X_test)
# 
#     plt.figure()
#     shap.plots.waterfall(shap_values[0, :, 1], show=False)
#     plt.savefig("waterfall_plot.png", dpi=300, bbox_inches="tight")
# 
#     plt.figure()
#     shap.summary_plot(shap_values.values[:, :, 1], X_test, plot_type="bar", show=False)
#     plt.savefig("summary_plot.png", dpi=300, bbox_inches="tight")
# 
# if __name__ == "__main__":
#     main()
#

!python app.py

from google.colab import files
files.download("waterfall_plot.png")
files.download("summary_plot.png")